repositories:
  istio:
    github:
      task:
        owner: servicemesher
        repository: istio-official-translation
      code:
        owner: istio
        repository: istio.io
    valid_extensions:
    - ".md"
    labels:
    - priority/P0
    branches:
    - name: "1.1"
      target_branch: release-1.1
      path: "/errbot/repository/1.1"
      url_prefix:
        source: "https://github.com/istio/istio.io/tree/release-1.1/content"
      labels:
      - version/1.1
      ignore: ['^\/test\/.*?$', '^\/boilerplates\/test.*?$']
    source:
      name: en
      path: content
    languages:
    - name: zh
      path: content_zh
      labels:
      - lang/zh
      target_labels:
      - translation/chinese
    status:
      pushed: pushed
      merged: merged
      pending: pending
      working: translating