repositories:
  istio:
    github:
      task:
        owner: servicemesher
        repository: istio-official-translation
      code:
        owner: istio
        repository: istio.io
    valid_extensions:
    - ".md"
    priorities:
    - patterns: ['^\/blog\/.*?$', '^\/news\/.*?$', '^\/faq\/.*?$', '^\/about\/.*?$']
      labels: ['priority/P3']
    - patterns: ['^\/docs\/reference\/.*?$']
      labels: ['priority/P2']
    - patterns: ['^\/docs\/ops\/performance-and-scalability\/.*?$', '^\/docs\/ops\/diagnostic-tools\/.*?$', '^\/docs\/examples\/multicluster\/.*?$', '^\/docs\/examples\/mesh-expansion\/.*?$', '^\/docs\/setup\/upgrade\/.*?$', '^\/docs\/setup\/deployment-models\/.*?$', '^\/docs\/setup\/additional-setup\/.*?$']
      labels: ['priority/P1']
    - patterns: ['^\/.*?$']
      labels: ['priority/P0']
    branches:
    - name: "master"
      target_branch: master
      path: "/errbot/repository/master"
      url_prefix:
        source: "https://github.com/istio/istio.io/tree/master/content/en"
        target: "https://github.com/istio/istio.io/tree/master/content/zh"
      labels:
      - version/master
      ignore: ['^\/test\/.*?$', '^\/boilerplates\/test.*?$']
    source:
      name: en
      path: content/en
    languages:
    - name: zh
      path: content/zh
      labels:
      - lang/zh
      target_labels:
      - translation/chinese
    status:
      pushed: pushed
      merged: merged
      pending: pending
      working: translating